services:
  the-seal:
    container_name: the-seal
    build: ./compose
    restart: always
    env_file:
      - .env
    volumes:
      - ./compose/nginx.conf:/etc/nginx/conf.d/default.conf
      - "./src/dist:/usr/share/nginx/html"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.the-seal.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.the-seal.entrypoints=websecure"
      - "traefik.http.routers.the-seal.tls.certresolver=myresolver"
    networks:
      - web

networks:
  web:
    name: web
    external: true
