version: '3.9'

services:
  the-seal:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - "./src/dist:/usr/share/nginx/html"
      - "./src:/src"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.the-seal.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.the-seal.entrypoints=websecure"
      - "traefik.http.routers.the-seal.tls.certresolver=myresolver"
    networks:
      - web

networks:
  web:
    name: web
    external: true
